# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.growPartition = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5ac6bc22-19d3-43ab-a922-1d63e2f166d9";
      fsType = "ext4";
      autoResize = true;
    };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/33cee871-57cc-47c1-a39f-fae271cc3a9a";
    fsType = "ext4";
    options = [ "defaults" "nofail" ];
  };

  swapDevices =
    [ { device = "/var/lib/swapfile"; size = 8192; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

